services:
  postgres:
    container_name: libraryPet
    image: postgres
    environment:
      - 'POSTGRES_DB=library_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    networks:
      library-network:
        aliases:
          - library
networks:
  library-network:
    name: 'our_library_network'
